apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Default target namespace (override in an overlay).
namespace: sardeenz

resources:
  - scc.yaml
  - rbac.yaml
  - pvcs.yaml
  - worker-deployment.yaml
  - module-pvc-write-protection.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: sardeenz
    includeSelectors: false
