apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sardeenz

resources:
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - valkey-pvc.yaml
  - valkey-service.yaml
  - valkey-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: sardeenz
    includeSelectors: false
