apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sardeenz

resources:
  - service.yaml
  - admin-service.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: sardeenz
    includeSelectors: false
