apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sardeenz

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - service.yaml
  - deployment.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: sardeenz
    includeSelectors: false
